<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Event.Streaming.Out</AssemblyName>
    <RootNamespace>Event.Streaming.Out</RootNamespace>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Event.Streaming.Processing" VersionOverride="1.0.2-alpha" />
  </ItemGroup>
</Project>